In [ ]:
!pip install -U spacy==3.*
!python -m spacy download en_core_web_sm
!python -m spacy info

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!ls "/content/drive/MyDrive/txtfiles"

'2026 Technical Resume - Srideep Dornala.pdf.txt'  'Perfect Resume.txt'
'Embedded Software Engineer.gdoc'		   'Sales Consultant Resume.gdoc'
'Embedded Software Engineer.txt'		   'Sales Consultant Resume.txt'
'Find the Right Job description.txt'		   'Software Architect.gdoc'
'Perfect Resume.gdoc'				   'Software Architect.txt'


In [ ]:
!cd "/content/drive/MyDrive/txtfiles"

In [ ]:
import string

nltk.download('stopwords')
stopWords = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
def preprocess(jobDesc):
  jobDescArray = jobDesc.read().split('qp')
  jobDescString = jobDescArray[0].translate(str.maketrans('', '', string.punctuation))
  lines = re.split('●|•|\n| ', jobDescString)
  lines = list(filter(None, lines))
  filteredLines = []

  for i in lines:
    if i not in stopWords:
      filteredLines.append(i)

  finalJobDesc = " ".join(filteredLines)

  return finalJobDesc

In [ ]:
jobDesc = open("Find the Right Job description.txt", "r")
perfectResume = open("Perfect Resume.txt", "r")
SalesConsultant = open("Sales Consultant Resume.txt", "r")
EmbeddedSoftwareEngineer = open("Embedded Software Engineer.txt", "r")
SoftwareArchitect = open("Software Architect.txt", "r")
myResume = open("2026 Technical Resume - Srideep Dornala.pdf.txt", "r")

In [ ]:
perfectResume = preprocess(perfectResume)
SalesConsultant = preprocess(SalesConsultant)
EmbeddedSoftwareEngineer = preprocess(EmbeddedSoftwareEngineer)
SoftwareArchitect = preprocess(SoftwareArchitect)
jobDesc = preprocess(jobDesc)
myResume = preprocess(myResume)

Data Preprocessing Complete

In [ ]:
import spacy
from scipy import spatial
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
vectorizer = CountVectorizer()

In [ ]:
corpus = []
corpus.append(jobDesc)
corpus.append(myResume)
corpus.append(perfectResume)
corpus.append(SalesConsultant)
corpus.append(EmbeddedSoftwareEngineer)
corpus.append(SoftwareArchitect)

In [ ]:
bow = vectorizer.fit_transform(corpus)

In [ ]:
nlp = spacy.load('en_core_web_sm')

In [ ]:
def spacy_tokenizer(doc):
  return [t.text for t in nlp(doc) if not t.is_punct]

In [ ]:
vectorizer = CountVectorizer(tokenizer=spacy_tokenizer, lowercase=False, binary=True)
bow = vectorizer.fit_transform(corpus)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [ ]:
print(vectorizer.get_feature_names_out())
vectorizer.vocabulary_

['\x0c' '\x0c\x0c' '\x0c ' '03' '10' '100' '15' '15701600' '17' '19' '20'
 '200' '2013' '2015' '2017' '2018' '2019' '2020' '2021' '2022' '2023'
 '20232024' '2024' '2026' '2385550102' '25' '3175550145' '360'
 '3905550145' '40' '45' '46' '5' '5102032056' '55' '9008' '95' 'ACM' 'AI'
 'AIML' 'API' 'APIs' 'ASPIRING' 'AWS' 'Actively' 'Agile' 'Algorithms'
 'Analysis' 'Analyzed' 'Applied' 'April' 'ArcGIS' 'Architect' 'Archive'
 'Artificial' 'Assistant' 'Aug' 'August' 'Autonomy' 'Availability'
 'Available' 'BS' 'Bachelors' 'Bay' 'Bayes' 'Be' 'Blue' 'Bootstrap' 'C'
 'CA' 'CAD' 'CI' 'CLUB' 'COLABERRY' 'CSS' 'CSSLP' 'CT' 'California'
 'Certifications' 'Certified' 'Chicago' 'Chrome' 'Clearwater' 'Club' 'Co'
 'Cody' 'Collaborated' 'Collaborates' 'College' 'Colleges' 'Committed'
 'Communicates' 'Communication' 'Community' 'Computer' 'Computing'
 'Conducted' 'Consultant' 'Contributed' 'Contributes' 'Core' 'Coursework'
 'Crane' 'Created' 'Creative' 'Current' 'DATA' 'DIRECTED' 'DORNALA' 'Data'
 'Debugs'

{'Find': 152,
 'Right': 290,
 'Job': 201,
 'Project': 267,
 'Position': 260,
 'Core': 100,
 'AI': 38,
 'Software': 316,
 'Engineer': 137,
 'Responsibilities': 289,
 'Collaborates': 87,
 'crossfunctional': 435,
 'team': 728,
 'discover': 455,
 'machine': 560,
 'learning': 549,
 'algorithms': 363,
 'prototype': 650,
 'testing': 734,
 'production': 632,
 'Ensures': 141,
 'software': 701,
 'standards': 715,
 'met': 576,
 'May': 228,
 'use': 758,
 'multisystems': 588,
 'multiagent': 585,
 'approaches': 373,
 'architect': 377,
 'design': 448,
 'systems': 723,
 'Has': 175,
 'great': 508,
 'passion': 606,
 'Modeling': 233,
 'Simulation': 312,
 'Autonomy': 58,
 'Development': 120,
 'good': 505,
 'understanding': 749,
 'applications': 371,
 'training': 744,
 'process': 628,
 'lead': 546,
 'development': 453,
 'implementation': 521,
 'cuttingedge': 439,
 'models': 581,
 'tailored': 724,
 'searching': 690,
 'matching': 573,
 'Your': 352,
 'role': 680,
 'involve': 538,
 'designing': 449,
 'architec

In [ ]:
doc1_vs_doc2 = 1 - spatial.distance.cosine(bow[0].toarray()[0], bow[1].toarray()[0])
print(f"Doc 1 vs Doc 2: {doc1_vs_doc2}")

Doc 1 vs Doc 2: 0.10261133758867635


In [ ]:
print(cosine_similarity(bow))

[[1.         0.10261134 0.33228662 0.0749195  0.11356994 0.0953155 ]
 [0.10261134 1.         0.11414708 0.0352476  0.07087864 0.05913411]
 [0.33228662 0.11414708 1.         0.0579771  0.1177059  0.0922009 ]
 [0.0749195  0.0352476  0.0579771  1.         0.08757784 0.13672249]
 [0.11356994 0.07087864 0.1177059  0.08757784 1.         0.15583207]
 [0.0953155  0.05913411 0.0922009  0.13672249 0.15583207 1.        ]]


First row above shows the similarity of each of the documents to the original Job Description. The second value shows the similarity of my Resume, the third value is the perfect resume, the fourth value is the embedded software engineer's resume, and the fifth value is the sales architect.

In [ ]:
cosine_similarity(bow)[0]

array([1.        , 0.10261134, 0.33228662, 0.0749195 , 0.11356994,
       0.0953155 ])

In [ ]:
import numpy as np

scores = cosine_similarity(bow)[0]

scores = [i * 100 for i in scores]

print(scores)

scores = np.log(scores)
scores = np.log(scores)

print(scores)

[100.00000000000013, 10.261133758867635, 33.22866153872883, 7.491950477531918, 11.356993918783347, 9.531550041235784]
[1.52717963 0.84516559 1.25373758 0.70003797 0.88782284 0.81297583]


In [ ]:
scores2 = []

perfectScore = scores[2]

for i in scores:
  scores2.append(i/perfectScore)

finalScores = []

for i in scores2:
  finalScores.append(i*5)

print(finalScores)

[6.090507496333083, 3.3705840981992536, 5.0, 2.791804213622473, 3.5407044387085356, 3.242208927875596]
